export const COMPETITION_LIST_REQUEST = "COMPETITION_LIST_REQUEST";
export const COMPETITION_LIST_SUCCESS = "COMPETITION_LIST_SUCCESS";
export const COMPETITION_LIST_FAIL = "COMPETITION_LIST_FAIL";

export const COMPETITION_DETAILS_REQUEST = "COMPETITION_DETAILS_REQUEST";
export const COMPETITION_DETAILS_SUCCESS = "COMPETITION_DETAILS_SUCCESS";
export const COMPETITION_DETAILS_FAIL = "COMPETITION_DETAILS_FAIL";

export const COMPETITION_REGISTER_REQUEST = "COMPETITION_REGISTER_REQUEST";
export const COMPETITION_REGISTER_SUCCESS = "COMPETITION_REGISTER_SUCCESS";
export const COMPETITION_REGISTER_FAIL = "COMPETITION_REGISTER_FAIL";
export const COMPETITION_REGISTER_RESET = "COMPETITION_REGISTER_RESET";

export const COMPETITION_UPDATE_REQUEST = "COMPETITION_UPDATE_REQUEST";
export const COMPETITION_UPDATE_SUCCESS = "COMPETITION_UPDATE_SUCCESS";
export const COMPETITION_UPDATE_FAIL = "COMPETITION_UPDATE_FAIL";

export const COMPETITION_MINE_REQUEST = "COMPETITION_MINE_REQUEST";
export const COMPETITION_MINE_SUCCESS = "COMPETITION_MINE_SUCCESS";
export const COMPETITION_MINE_FAIL = "COMPETITION_MINE_FAIL";