export const EQUIPE_ADD_PLAYER_REQUEST = 'EQUIPE_ADD_PLAYER_REQUEST';
export const EQUIPE_ADD_PLAYER_SUCCESS = 'EQUIPE_ADD_PLAYER_SUCCESS';
export const EQUIPE_ADD_PLAYER_FAIL = 'EQUIPE_ADD_PLAYER_FAIL';
export const EQUIPE_ADD_PLAYER_RESET = 'EQUIPE_ADD_PLAYER_RESET';
export const EQUIPE_REMOVE_PLAYER_REQUEST = 'EQUIPE_REMOVE_PLAYER_REQUEST';
export const EQUIPE_REMOVE_PLAYER_SUCCESS = 'EQUIPE_REMOVE_PLAYER_SUCCESS';
export const EQUIPE_REMOVE_PLAYER_FAIL = 'EQUIPE_REMOVE_PLAYER_FAIL';