export const EQUIPE_DETAILS_REQUEST = "EQUIPE_DETAILS_REQUEST";
export const EQUIPE_DETAILS_SUCCESS = "EQUIPE_DETAILS_SUCCESS";
export const EQUIPE_DETAILS_FAIL = "EQUIPE_DETAILS_FAIL";

export const EQUIPE_ADD_PLAYER_REQUEST = 'EQUIPE_ADD_PLAYER_REQUEST';
export const EQUIPE_ADD_PLAYER_SUCCESS = 'EQUIPE_ADD_PLAYER_SUCCESS';
export const EQUIPE_ADD_PLAYER_FAIL = 'EQUIPE_ADD_PLAYER_FAIL';
export const EQUIPE_ADD_PLAYER_RESET = 'EQUIPE_ADD_PLAYER_RESET';

export const EQUIPE_REMOVE_PLAYER_REQUEST = 'EQUIPE_REMOVE_PLAYER_REQUEST';
export const EQUIPE_REMOVE_PLAYER_SUCCESS = 'EQUIPE_REMOVE_PLAYER_SUCCESS';
export const EQUIPE_REMOVE_PLAYER_FAIL = 'EQUIPE_REMOVE_PLAYER_FAIL';

export const EQUIPE_CAPITAINE_REQUEST = 'EQUIPE_CAPITAINE_REQUEST';
export const EQUIPE_CAPITAINE_SUCCESS = 'EQUIPE_CAPITAINE_SUCCESS';
export const EQUIPE_CAPITAINE_FAIL = 'EQUIPE_CAPITAINE_FAIL';

export const EQUIPE_CREATE_REQUEST = 'EQUIPE_CREATE_REQUEST';
export const EQUIPE_CREATE_SUCCESS = 'EQUIPE_CREATE_SUCCESS';
export const EQUIPE_CREATE_FAIL = 'EQUIPE_CREATE_FAIL';
export const EQUIPE_CREATE_RESET = 'EQUIPE_CREATE_RESET';

export const EQUIPE_MINE_REQUEST = 'EQUIPE_MINE_REQUEST';
export const EQUIPE_MINE_SUCCESS = 'EQUIPE_MINE_SUCCESS';
export const EQUIPE_MINE_FAIL = 'EQUIPE_MINE_FAIL';