export const EVALUATION_CREATE_REQUEST = "EVALUATION_CREATE_REQUEST";
export const EVALUATION_CREATE_SUCCESS = "EVALUATION_CREATE_SUCCESS";
export const EVALUATION_CREATE_FAIL = "EVALUATION_CREATE_FAIL";
