export const FOOTBALLEUR_REGISTER_REQUEST = 'FOOTBALLEUR_REGISTER_REQUEST';
export const FOOTBALLEUR_REGISTER_SUCCESS = 'FOOTBALLEUR_REGISTER_SUCCESS';
export const FOOTBALLEUR_REGISTER_FAIL = 'FOOTBALLEUR_REGISTER_FAIL';

export const FOOTBALLEUR_SIGNIN_REQUEST = 'FOOTBALLEUR_SIGNIN_REQUEST';
export const FOOTBALLEUR_SIGNIN_SUCCESS = 'FOOTBALLEUR_SIGNIN_SUCCESS';
export const FOOTBALLEUR_SIGNIN_FAIL = 'FOOTBALLEUR_SIGNIN_FAIL';

export const FOOTBALLEUR_SIGNOUT = 'FOOTBALLEUR_SIGNOUT';

export const FOOTBALLEUR_UPDATE_REQUEST = 'FOOTBALLEUR_UPDATE_REQUEST';
export const FOOTBALLEUR_UPDATE_SUCCESS = 'FOOTBALLEUR_UPDATE_SUCCESS';
export const FOOTBALLEUR_UPDATE_FAIL = 'FOOTBALLEUR_UPDATE_FAIL';

export const FOOTBALLEUR_LIST_REQUEST = 'FOOTBALLEUR_LIST_REQUEST'
export const FOOTBALLEUR_LIST_SUCCESS = 'FOOTBALLEUR_LIST_SUCCESS'
export const FOOTBALLEUR_LIST_FAIL = 'FOOTBALLEUR_LIST_FAIL'

export const FOOTBALLEUR_DELETE_REQUEST = 'FOOTBALLEUR_DELETE_REQUEST'
export const FOOTBALLEUR_DELETE_SUCCESS = 'FOOTBALLEUR_DELETE_SUCCESS'
export const FOOTBALLEUR_DELETE_FAIL = 'FOOTBALLEUR_DELETE_FAIL'
 
export const FOOTBALLEUR_DETAILS_REQUEST = "FOOTBALLEUR_DETAILS_REQUEST";
export const FOOTBALLEUR_DETAILS_SUCCESS = "FOOTBALLEUR_DETAILS_SUCCESS";
export const FOOTBALLEUR_DETAILS_FAIL = "FOOTBALLEUR_DETAILS_FAIL";

export const FOOTBALLEUR_SEARCH_REQUEST = "FOOTBALLEUR_SEARCH_REQUEST";
export const FOOTBALLEUR_SEARCH_SUCCESS = "FOOTBALLEUR_SEARCH_SUCCESS";
export const FOOTBALLEUR_SEARCH_FAIL = "FOOTBALLEUR_SEARCH_FAIL";