export const INVITATION_SEND_REQUEST = "INVITATION_SEND_REQUEST";
export const INVITATION_SEND_SUCCESS = "INVITATION_SEND_SUCCESS";
export const INVITATION_SEND_FAIL = "INVITATION_SEND_FAIL";

export const INVITATION_LIST_MY_REQUEST = "INVITATION_LIST_MY_REQUEST";
export const INVITATION_LIST_MY_SUCCESS = "INVITATION_LIST_MY_SUCCESS";
export const INVITATION_LIST_MY_FAIL = "INVITATION_LIST_MY_FAIL";