export const MATCH_CREATE_REQUEST = "MATCH_CREATE_REQUEST";
export const MATCH_CREATE_SUCCESS = "MATCH_CREATE_SUCCESS";
export const MATCH_CREATE_FAIL = "MATCH_CREATE_FAIL";

export const MATCH_LIST_REQUEST = "MATCH_LIST_REQUEST";
export const MATCH_LIST_SUCCESS = "MATCH_LIST_SUCCESS";
export const MATCH_LIST_FAIL = "MATCH_LIST_FAIL";

export const MATCH_DETAILS_REQUEST = "MATCH_DETAILS_REQUEST";
export const MATCH_DETAILS_SUCCESS = "MATCH_DETAILS_SUCCESS";
export const MATCH_DETAILS_FAIL = "MATCH_DETAILS_FAIL";

export const MATCH_JOIN_REQUEST = "MATCH_JOIN_REQUEST";
export const MATCH_JOIN_SUCCESS = "MATCH_JOIN_SUCCESS";
export const MATCH_JOIN_FAIL = "MATCH_JOIN_FAIL";

// export const MATCH_RATE_REQUEST = "MATCH_RATE_REQUEST";
// export const MATCH_RATE_SUCCESS = "MATCH_RATE_SUCCESS";
// export const MATCH_RATE_FAIL = "MATCH_RATE_FAIL";
