export const MATCH_CREATE_REQUEST = "MATCH_CREATE_REQUEST";
export const MATCH_CREATE_SUCCESS = "MATCH_CREATE_SUCCESS";
export const MATCH_CREATE_FAIL = "MATCH_CREATE_FAIL";

export const MATCH_LIST_REQUEST = "MATCH_LIST_REQUEST";
export const MATCH_LIST_SUCCESS = "MATCH_LIST_SUCCESS";
export const MATCH_LIST_FAIL = "MATCH_LIST_FAIL";

export const MATCH_DETAILS_REQUEST = "MATCH_DETAILS_REQUEST";
export const MATCH_DETAILS_SUCCESS = "MATCH_DETAILS_SUCCESS";
export const MATCH_DETAILS_FAIL = "MATCH_DETAILS_FAIL";

export const MATCH_JOIN_REQUEST = "MATCH_JOIN_REQUEST";
export const MATCH_JOIN_SUCCESS = "MATCH_JOIN_SUCCESS";
export const MATCH_JOIN_FAIL = "MATCH_JOIN_FAIL";

export const MATCH_LIST_MY_REQUEST = "MATCH_LIST_MY_REQUEST";
 export const MATCH_LIST_MY_SUCCESS = "MATCH_LIST_MY_SUCCESS";
 export const MATCH_LIST_MY_FAIL = "MATCH_LIST_MY_FAIL";

 export const MATCH_UPDATE_REQUEST = "MATCH_UPDATE_REQUEST";
export const MATCH_UPDATE_SUCCESS = "MATCH_UPDATE_SUCCESS";
export const MATCH_UPDATE_FAIL = "MATCH_UPDATE_FAIL";

export const MATCH_DELETE_REQUEST = "MATCH_DELETE_REQUEST";
export const MATCH_DELETE_SUCCESS = "MATCH_DELETE_SUCCESS";
export const MATCH_DELETE_FAIL = "MATCH_DELETE_FAIL";

export const MATCH_JOIN_EQUIPE_REQUEST = 'MATCH_JOIN_EQUIPE_REQUEST';
export const MATCH_JOIN_EQUIPE_SUCCESS = 'MATCH_JOIN_EQUIPE_SUCCESS';
export const MATCH_JOIN_EQUIPE_FAIL = 'MATCH_JOIN_EQUIPE_FAIL';


export const MATCH_ADD_SCORE_REQUEST = "MATCH_ADD_SCORE_REQUEST";
export const MATCH_ADD_SCORE_SUCCESS = "MATCH_ADD_SCORE_SUCCESS";
export const MATCH_ADD_SCORE_FAIL = "MATCH_ADD_SCORE_FAIL";