export const NOTIFICATION_ADD = "NOTIFICATION_ADD";
export const NOTIFICATION_CLEAR = "NOTIFICATION_CLEAR";
export const NOTIFICATION_RESET = "NOTIFICATION_RESET";
export const NOTIFICATION_LOAD_SUCCESS = "NOTIFICATION_LOAD_SUCCESS";
export const NOTIFICATION_LOAD_FAIL = "NOTIFICATION_LOAD_FAIL";
export const NOTIFICATION_MARK_READ = "NOTIFICATION_MARK_READ";
