export const PROPRIETAIRE_REGISTER_REQUEST = "PROPRIETAIRE_REGISTER_REQUEST";
export const PROPRIETAIRE_REGISTER_SUCCESS = "PROPRIETAIRE_REGISTER_SUCCESS";
export const PROPRIETAIRE_REGISTER_FAIL = "PROPRIETAIRE_REGISTER_FAIL";

export const PROPRIETAIRE_SIGNIN_REQUEST = "PROPRIETAIRE_SIGNIN_REQUEST";
export const PROPRIETAIRE_SIGNIN_SUCCESS = "PROPRIETAIRE_SIGNIN_SUCCESS";
export const PROPRIETAIRE_SIGNIN_FAIL = "PROPRIETAIRE_SIGNIN_FAIL";

export const PROPRIETAIRE_SIGNOUT = "PROPRIETAIRE_SIGNOUT";

export const PROPRIETAIRE_UPDATE_REQUEST = "PROPRIETAIRE_UPDATE_REQUEST";
export const PROPRIETAIRE_UPDATE_SUCCESS = "PROPRIETAIRE_UPDATE_SUCCESS";
export const PROPRIETAIRE_UPDATE_FAIL = "PROPRIETAIRE_UPDATE_FAIL";

export const PROPRIETAIRE_DELETE_REQUEST = "PROPRIETAIRE_DELETE_REQUEST";
export const PROPRIETAIRE_DELETE_SUCCESS = "PROPRIETAIRE_DELETE_SUCCESS";
export const PROPRIETAIRE_DELETE_FAIL = "PROPRIETAIRE_DELETE_FAIL";

export const PROPRIETAIRE_LIST_REQUEST = "PROPRIETAIRE_LIST_REQUEST";
export const PROPRIETAIRE_LIST_SUCCESS = "PROPRIETAIRE_LIST_SUCCESS";
export const PROPRIETAIRE_LIST_FAIL = "PROPRIETAIRE_LIST_FAIL";
