export const TERRAIN_CREATE_REQUEST = "TERRAIN_CREATE_REQUEST";
export const TERRAIN_CREATE_SUCCESS = "TERRAIN_CREATE_SUCCESS";
export const TERRAIN_CREATE_FAIL = "TERRAIN_CREATE_FAIL";

export const TERRAIN_MINE_REQUEST = "TERRAIN_MINE_REQUEST";
export const TERRAIN_MINE_SUCCESS = "TERRAIN_MINE_SUCCESS";
export const TERRAIN_MINE_FAIL = "TERRAIN_MINE_FAIL";

export const TERRAIN_LIST_REQUEST = "TERRAIN_LIST_REQUEST";
export const TERRAIN_LIST_SUCCESS = "TERRAIN_LIST_SUCCESS";
export const TERRAIN_LIST_FAIL = "TERRAIN_LIST_FAIL";

export const TERRAIN_UPDATE_REQUEST = "TERRAIN_UPDATE_REQUEST";
export const TERRAIN_UPDATE_SUCCESS = "TERRAIN_UPDATE_SUCCESS";
export const TERRAIN_UPDATE_FAIL = "TERRAIN_UPDATE_FAIL";

export const TERRAIN_DELETE_REQUEST = "TERRAIN_DELETE_REQUEST";
export const TERRAIN_DELETE_SUCCESS = "TERRAIN_DELETE_SUCCESS";
export const TERRAIN_DELETE_FAIL = "TERRAIN_DELETE_FAIL";
